### ISSUE TITLE
info code

### ISSUE THREAD

**Issue by ArkZoneps4** [Vislate/DayZ-Console-Killfeed#1]
Hi Victor
i did some adjustment on the code the check if its running on nitrado ark server

WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
INFO:discord.client:logging in using static token
INFO:discord.gateway:Shard ID None has sent the IDENTIFY payload.
INFO:discord.gateway:Shard ID None has connected to Gateway: ["gateway-prd-main-b5rk",{"micros":36072,"calls":["discord-sessions-prd-2-49",{"micros":35114,"calls":["start_session",{"micros":27164,"calls":["api-prd-main-6z6d",{"micros":24092,"calls":["get_user",{"micros":2342},"add_authorized_ip",{"micros":1217},"get_guilds",{"micros":4337},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":1,"calls":[]},"presence_connect",{"micros":7290,"calls":[]}]}]}] (Session ID: 682e0f6b4476541a64e4bf1094e9170b).
INFO:root:Started bot | Made by vic#1337 (https://killfeed.me)
INFO:root:Downloading logfile for 6994781

**Comment by Locvic** [comment]
The code is written for DayZ specifically. This will not work for ARK out of the box as many of the regular expressions used are DayZ specific.

If you wish to create a fork of this and make it for ARK I won't be able to help you, as it's not related to DayZ.
