### ISSUE TITLE
Killfeed repeating

### ISSUE THREAD

**Issue by Sdefref** [Vislate/DayZ-Console-Killfeed#2]
Today the killfeed started repeating its feeds on every download/checking of the log file.

**Comment by matespinda01** [comment]
Same for me, i have a workaround.
Create a file and open it with "a+".
Check if the death event is in your file.
append the whole line to your new file.
If not do the announcments, else do nothing

**Comment by Sdefref** [comment]
Thx for your reply.

Im confured of what you mean to do...

Repeating starts when logfile is not been refreshed, I mean new log file hasnt been crated
and it continues with the old log file from nitrado.
Log has a line "AdminLog started" and normally only 1 line
When logs get bugged then there can be more then 1 line of "AdminLog started" and thats where the issue is at.

Anyway, could you explain a bit more of what you mean.

**Comment by matespinda01** [comment]
I'll fork the repo and publish the version whats working for me. Give me a couple days I'm not at home

**Comment by Sdefref** [comment]
> I'll fork the repo and publish the version whats working for me. Give me a couple days I'm not at home

Hey there, I do am still waiting :)
I have been trying to figure it out on my own but my python coding is not perfect.
If you still be willing to help me out it would mean a lot to me, today feeds started to repeat again and had to shut them off.

**Comment by Sdefref** [comment]
nvm, I finally figured it out, mode a+ was misleading had to use r+
my feeds now never be repeated again.

created new file.
added some new lines of codes so it would still check the log what the bot downloads from nitrado,
when theres death event like player killed player and normally it gives feed right away

now when it detects player killed player event from downloaded log file it checking new file and if that event is not in the log
it sends the feed out,
but if it has the log in new file it just does nothing and continues as normally.

**Comment by Locvic** [comment]
sorry its different on my system a+ works fine for me but some others might have to change it to "r+" thank you for explaining this!
